services:
  fastify:
    build: ./Backend
    container_name: fastify
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - sqlite:/app/data
    environment:
      SQLITE_PATH=/app/data/database.db

volumes:
  sqlite: