services:
  fastify:
    build: ./Backend
    container_name: fastify
    ports:
      - "3000:3000"
    command: start
    volumes:
      - ./Backend:/app
      - sqlite:/app/data
    require:
      fastify

  typescript:
    build: ./Frontend
    container_name: typescript
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
      - /app/node_modules


volumes:
  sqlite:
