
services:
  fastify:
    build: ./Backend
    container_name: fastify
    command: npm run start
    ports:
      - "3000"
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/scripts:/app/scripts
      - sqlite:/app/data
      - user_avatars:/app/uploads/avatars
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - OTP_SECRET=${OTP_SECRET}
      - API_DOMAIN_NAME=${API_DOMAIN_NAME}
      - FRONTEND_DOMAIN_NAME=${FRONTEND_DOMAIN_NAME}
      - FT_CLIENT_ID=${FT_CLIENT_ID}
      - FT_CLIENT_SECRET=${FT_CLIENT_SECRET}
    networks:
      - app-network

  typescript:
    build: ./Frontend
    container_name: typescript
    ports:
      - "8080"
    volumes:
      - ./Frontend:/app
    environment:
      - VITE_JWT_SECRET=${JWT_SECRET}
      - VITE_APP_SECRET_KEY=${APP_SECRET_KEY}
      - VITE_API_DOMAIN_NAME=${API_DOMAIN_NAME}
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8443:443"   # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - fastify
      - typescript
    networks:
      - app-network
  

volumes:
  sqlite:
  user_avatars:

networks:
  app-network:
    driver: bridge
