services:
  fastify:
    build: ./Backend
    container_name: fastify
    ports:
      - "8443:8443"
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/scripts:/app/scripts
      - sqlite:/app/data
      - user_avatars:/app/uploads/avatars
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_SECRET_KEY=${APP_SECRET_KEY}

  typescript:
    build: ./Frontend
    container_name: typescript
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_SECRET_KEY=${APP_SECRET_KEY}

  jasmine:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.test
    container_name: jasmine
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CI=true
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "9222:9222"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_SECRET_KEY=${APP_SECRET_KEY}

volumes:
  sqlite:
  user_avatars:
