services:
  fastify:
    build: ./Backend
    container_name: fastify
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./Backend/src:/app/src
      - ./Backend/scripts:/app/scripts
      - ./Backend/tests:/app/tests
      - sqlite:/app/data
      - user_avatars:/app/uploads/avatars
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - OTP_SECRET=${OTP_SECRET}
      - API_DOMAIN_NAME=${API_DOMAIN_NAME}

  typescript:
    build: ./Frontend
    container_name: typescript
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
    environment:
      - VITE_JWT_SECRET=${JWT_SECRET}
      - VITE_APP_SECRET_KEY=${APP_SECRET_KEY}
      - VITE_API_DOMAIN_NAME=${API_DOMAIN_NAME}

volumes:
  sqlite:
  user_avatars:
