services:
  fastify:
    build: ./Backend
    container_name: fastify
    ports:
      - "3000:3000"
    command: dev
    volumes:
      - ./Backend:/app
      - sqlite:/app/data

  typescript:
    build: ./Frontend
    container_name: typescript
    ports:
      - "8080:8080"
    command: dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # to allow for reloading (website update as code change)
      # setting the docker to check the file as written in the src/ folder
      # at determinate intervals
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200

volumes:
  sqlite:
